apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu-pod
    dev: sam
    env: test
    team: hive
  name: ubuntu-pod
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    stdin: true
    tty: true
